import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ margin: 0, padding: 0 }}
      >
        {/* 💛 Home Button Bar */}
        <div
          style={{
            width: "100%",
            padding: "12px 20px",
            background: "#fff",
            borderBottom: "1px solid #eee",
            display: "flex",
            justifyContent: "flex-start",
            alignItems: "center",
            position: "sticky",
            top: 0,
            zIndex: 1000,
          }}
        >
          <Link
            href="/"
            style={{
              fontSize: "18px",
              fontWeight: "700",
              textDecoration: "none",
              color: "#333",
              padding: "6px 14px",
              background: "#f0f0f0",
              borderRadius: "999px",
              border: "1px solid #ddd",
            }}
          >
            Home
          </Link>
        </div>

        {/* Page Content */}
        {children}
        <Analytics />
      </body>
    </html>
  );
}
